config_version = 1
repo_root = "/home/gig/local_repos/gigpkgs"
rolling_branch = "rolling"
stable_branch = "master"
roll_prefix = "roll/"
version_gate = false
tag_on_promote = false
push_tag = false
mode = "manage"
username = "gig"
hosts = []
roll_to_rolling_gates = ["nix flake check --no-build --accept-flake-config"]
rolling_to_main_gates = ["nix flake check --no-build --accept-flake-config"]
host_gates = []
clean_protect = []

[host_active]
