config_version = 1
repo_root = "/home/gig/local_repos/gigpkgs"
rolling_branch = "master"
stable_branch = "rolling"
roll_prefix = "roll/"
username = "gig"
hosts = []
roll_to_rolling_gates = []
rolling_to_main_gates = []

[host_active]
