{
  description = "Gig's nixpkgs overlay";
  inputs = {
    # nixpkgs
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/master";
    # nixpkgs-pkgs-stable.url = "github:NixOS/nixpkgs/nixpkgs-26.05";

    # utlis
    pre-commit-hooks = {
      url = "github:cachix/git-hooks.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      ...
    }@inputs:
    let
      inherit (self) outputs;
      inherit (nixpkgs) lib;
      system = "x86_64-linux";
      configLib = import ./lib { inherit lib; };
      specialArgs = {
        inherit
          inputs
          outputs
          nixpkgs
          ;
      };
      customPkgs = import ./pkgs { inherit pkgs; };
      pkgs =
        import nixpkgs {
          inherit system;
          config = {
            allowUnfree = true;
          };
        }
        // customPkgs;
    in
    {
      overlays = import ./overlays { inherit inputs; };

      packages.${system} = import ./pkgs { inherit pkgs; };

      pre-commit-check = inputs.pre-commit-hooks.lib.${system}.run {
        src = ./.;
        hooks = {
          nixfmt = {
            enable = true;
            excludes = [
              ".*/hardware-configuration\\.nix$" # Exclude autogenerated files
            ];
          };
          statix = {
            enable = true;
          };
          deadnix = {
            enable = true;
            excludes = [
            ];
          };
          shellcheck = {
            enable = false;
            excludes = [
            ];
          };
          markdownlint = {
            enable = false;
          };
          yamllint = {
            enable = true;
            excludes = [
              ".github/workflows/flake-check.yml"
            ];
          };
          end-of-file-fixer = {
            enable = true;
          };
        };
      };

      checks.${system} = import ./checks {
        inherit
          self
          pkgs
          lib
          ;
      };

      devShells.${system}.default = pkgs.mkShell {
        NIX_CONFIG = "extra-experimental-features = nix-command flakes";

        nativeBuildInputs = builtins.attrValues {
          inherit (pkgs)
            git
            pre-commit
            lolcat
            nixfmt
            nil
            just
            lazygit
            statix
            deadnix
            nix
            fzf
            quick-results
            upjust
            locker
            ripgrep

            upignore
            ;
        };
        shellHook = ''
          ${self.pre-commit-check.shellHook}

          echo "Welcome to the gigpkgs devShell" | ${pkgs.lolcat}/bin/lolcat"
        '';
      };

      formatter.${system} = pkgs.nixpkgs-fmt;
    };
}
