{
  description = "Gig's nixpkgs overlay";
  inputs = {
    nixpkgs = "github:NixOS/nixpkgs/nixpkgs-26.05";
    nixpkgs-unstable = "github:NixOS/nixpkgs/master";
    # nixospkgs = "github:NixOS/nixpkgs/nixos-26.05";
  };

  outputs = {
    self,nixpkgs,...
  }@inputs:
    let
      inherit (self) outputs;
      inherit (nixpkgs) lib;
      system = "x86_64-linux";
      specialArgs = {
  inherit
    inputs
  outputs
  nixpkgs;
  };
      customPkgs = import ./pkgs {inherit pkgs;};
      pkgs = 
        import nixpkgs {
    inherit system;
    config = {
    allowUnfree=true;
  };
  }
  // customPkgs;
    in 
      packages.${system} = import ./pkgs {inherit pkgs;};
    {

  overlays = import ./overlays {inherit inputs;};

checks.${system} = import ./checks {
    inherit
  self
  pkgs 
  lib;
  }// pre-commit-check;

pre-commit-check = inputs.pre-commit-hooks.lib.${system}.run {
    src = ./.;
        hooks = {
          nixfmt = {
            enable = true;
            excludes = [
              ".*/hardware-configuration\\.nix$" # Exclude autogenerated files
            ];
          };
          statix = {
            enable = true;
          };
          deadnix = {
            enable = true;
            excludes = [
            ];
          };
          shellcheck = {
            enable = false;
            excludes = [
            ];
          };
          markdownlint = {
            enable = false;
          };
          yamllint = {
            enable = true;
            excludes = [
              ".github/workflows/flake-check.yml"
            ];
          };
          end-of-file-fixer = {
            enable = true;
          };
    };
  };

  devShells.${system}.default = pkgs.mkShell {
    NIX_CONFIG = "extra-experimental-features = nix-command flakes";

    nativeBuildInputs = builtins.attrValues {
    inherit (pkgs)
  git 
  pre-commit 
  lolcat 
  nixfmt 
  nil 
  just 
  lazygit 
  statix 
  deadnix 
  nix 
  fzf 
  quick-results
  upjust 
  locker 
  ripgrep;
  };
    shellHook = ''
    ${self.pre-commit-check.shellHook}

    echo "Welcome to the gigpkgs devShell" | ${pkgs.lolcat}/bin/lolcat"
  '';
  };

  formatter.${system} = pkgs.nixpkgs-fmt;
    };
}
